services:

  # configuração do prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'

  # configuração do loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" 
    volumes:
      - loki-data:/loki

  # configuração do promtail
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      # Monta o "socket" do Docker para que o Promtail possa ler os logs
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '-config.file=/etc/promtail/config.yml'
    depends_on:
      - loki 

  # configuração do tempo
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [-config.file=/etc/tempo/tempo-config.yml]
    volumes:
      - ./tempo/tempo-config.yml:/etc/tempo.yml
      - tempo-data:/tmp/tempo/trace
    ports:
      - "3200:3200" # Porta principal do Tempo (para Grafana)
      - "4317:4317" # OTLP gRPC (para o Collector)
      - "4318:4318" # OTLP HTTP (para o Collector)
    
  # configuração do otel-collector 
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    command: [--config=/etc/otel-config.yml]
    volumes:
      - ./otel-collector/otel-config.yml:/etc/otel-config.yml
    ports:
      - "14318:4318" # Recebe OTLP HTTP (mapeando para 14318 na máquina)
      - "14317:4317" # Recebe OTLP gRPC (mapeando para 14317)
    depends_on:
      - loki
      - prometheus
      - tempo

  # configuração do grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  tempo-data:
  grafana-data:
  loki-data: 